# La declaración de versión ya no se usa, está obsoleta
#version: '3' 

name: deaw04te02-antlopez

# Servicios a integrar
services: 
 
  # MySQL, contendrá las BD del proyecto PHP y Wordpress
  mysql:
    build:
      context: db/
      # Se pueden cambiar los valores mediante estos argumentos
      # Tendrán que coincidir con las variables de entorno y con los argumentos de Apache
      args:
        PHP_DB_NAME: 'dwes04'
        PHP_DB_USER: 'antlopez'
        PHP_DB_PASS: 'birt'
        WP_URL: 'http://localhost:8080/wordpress'
        WP_DB_NAME: 'wordpress'
        WP_DB_PREFIX: 'wp'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_ADMIN_USER: 'anton'
        WP_ADMIN_PASS: 'anton'
        WP_ADMIN_EMAIL: 'antlopez@birt.eus'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'dwes04'
      MYSQL_USER: 'antlopez'
      MYSQL_PASSWORD: 'birt'
    container_name: 'db'
    networks:
      - miapp

  # Apache, contendrá el proyecto PHP y también el proyecto Wordpress
  apache:
    build:
      context: apache/
      # Se pueden cambiar los valores de wp-config.php mediante estos argumentos
      args:
        PHP_DB_NAME: 'dwes04'
        PHP_DB_USER: 'antlopez'
        PHP_DB_PASS: 'birt'
        WP_DB_HOST: 'db'
        WP_DB_NAME: 'wordpress'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_DB_PREFIX: 'wp'
    ports:
      - 8080:80
    volumes:
      - proyecto:/usr/local/apache2/htdocs
    networks:
      - miapp

  php:
    build: php/
    # No es necesario exponer el puerto de PHP al host, ya que quien accede es el contendor de Apache
    # Podría incluso ser un problema de seguridad si no fuera una instalación local
    # ports:
    #   - 9000:9000
    volumes:
      - proyecto:/var/www/html
    networks:
      - miapp

  # PHPMyAdmin, para gestionar visualmente las bases de datos
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD: 
      PMA_HOST: db
    networks:
      - miapp

volumes: 
  proyecto:
networks:
  miapp:
    driver: bridge