# Versión utilizada ----------------> DEPRECATED
#version: '3' 

# Configuración de los servidores que vamos a necesitar
services: 
 
  # mysql es el nombre que vamos a dar a este primer servicio
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build:
      context: db/
      # Valores a usar por la instalación de Wordpress:
      args:
        WP_URL: 'http://localhost:8080/wordpress'
        WP_DB_NAME: 'wordpress'
        WP_DB_PREFIX: 'wp_'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_ADMIN_USER: 'anton'
        WP_ADMIN_PASS: 'anton'
        WP_ADMIN_EMAIL: 'antlopez@birt.eus'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'dwes'
      MYSQL_USER: 'dwes'
      MYSQL_PASSWORD: 'dwes'
    container_name: 'db'
    networks:
      - miapp

  # Wordpress se instalará dentro del servicio de Apache, junto al proyecto PHP
  apache:
    build:
      context: apache/
      args:
        WP_DB_HOST: 'db'
        WP_DB_NAME: 'wordpress'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_DB_PREFIX: 'wp_'
    ports:
      - 8080:80
    volumes:
      - proyecto:/var/www/html
    networks:
      - miapp

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html
    networks:
      - miapp

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD:  
      PMA_HOST: db
    networks:
      - miapp

  # WORDPRESS BITNAMI (https://www.docker.com/blog/how-to-dockerize-wordpress/)
  # wordpress:
  #   image: bitnami/wordpress:6.6.2
  #   ports:
  #     - '8082:8080'
  #   environment:
  #     WORDPRESS_DATABASE_HOST: 'db'
  #     WORDPRESS_DATABASE_PORT_NUMBER: 3306
  #     WORDPRESS_DATABASE_NAME: 'wordpress'
  #     WORDPRESS_DATABASE_USER: 'anton'
  #     WORDPRESS_DATABASE_PASSWORD: 'anton'
  #     WORDPRESS_TABLE_PREFIX: 'wp_'
  #     WORDPRESS_BLOG_NAME: 'Mi Blog'
  #     WORDPRESS_FIRST_NAME: 'Anton'
  #     WORDPRESS_LAST_NAME: 'Lopez Alvarez'
  #     WORDPRESS_USERNAME: anton
  #     WORDPRESS_PASSWORD: anton
  #     WORDPRESS_EMAIL: antlopez@birt.eus
  #     WORDPRESS_SMTP_HOST: 
  #     WORDPRESS_SMTP_PORT: 
  #     WORDPRESS_SMTP_USER: 
  #     WORDPRESS_SMTP_PASSWORD: 
  #   networks:
  #     - miapp

# WORDPRESS imagen oficial: https://hub.docker.com/_/wordpress
  # wordpress:
  #   image: wordpress:latest
  #   ports:
  #     - '8082:80'
  #   environment:
  #     WORDPRESS_DB_HOST: 'db'
  #     WORDPRESS_DB_NAME: 'wordpress'
  #     WORDPRESS_DB_USER: 'anton'
  #     WORDPRESS_DB_PASSWORD: 'anton'
  #   networks:
  #     - miapp


volumes: 
  proyecto:
networks:
  miapp:
    driver: bridge