# Versión utilizada ----------------> DEPRECATED
#version: '3' 

# Configuración de los servidores que vamos a necesitar
services: 
 
  # mysql es el nombre que vamos a dar a este primer servicio
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build: db/
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'dwes'
      MYSQL_USER: 'dwes'
      MYSQL_PASSWORD: 'dwes'
    container_name: 'db'
    networks:
      - miapp

  apache:
    build: apache/
    ports:
      - 8080:80
    volumes:
      - proyecto:/var/www/html/
    networks:
      - miapp

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - proyecto:/var/www/html/
    networks:
      - miapp

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8880:80
    environment:
      MYSQL_ROOT_PASSWORD:  
      PMA_HOST: db
    networks:
      - miapp

  # wordpress:
  #   image: wordpress
  #   ports:
  #     - 90:80
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: wordpress
  #     WORDPRESS_DB_USER: anton
  #     WORDPRESS_DB_PASSWORD: anton
  #     WORDPRESS_ADMIN_USERNAME: anton
  #     WORDPRESS_ADMIN_PASSWORD: anton
  #   networks:
  #     - miapp

volumes: 
  proyecto:
networks:
  miapp:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"