# Versión utilizada ----------------> DEPRECATED
#version: '3' 

# Configuración de los servidores que vamos a necesitar
services: 
 
  # mysql es el nombre que vamos a dar a este primer servicio
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build:
      context: db/
      # Valores a usar por la instalación de Wordpress:
      args:
        WP_URL: 'localhost:8080/wordpress'
        WP_DB_NAME: 'wordpress'
        WP_DB_PREFIX: 'wprb'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_ADMIN_USER: 'anton'
        WP_ADMIN_EMAIL: 'antlopez@birt.eus'
        # - WP_ADMIN_USER: 'anton'
        # - WP_ADMIN_PASS: 'anton'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: 'dwes'
      MYSQL_USER: 'dwes'
      MYSQL_PASSWORD: 'dwes'
    container_name: 'db'
    networks:
      - miapp

  apache:
    build:
      context: apache/
      args:
        WP_DB_HOST: 'db'
        WP_DB_NAME: 'wordpress'
        WP_DB_USER: 'anton'
        WP_DB_PASS: 'anton'
        WP_DB_PREFIX: 'wprb'
    ports:
      - 8080:80
    volumes:
      - php:/var/www/html/php
      - wordpress:/var/www/html/wordpress
    networks:
      - miapp

  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - php:/var/www/html/php
      - wordpress:/var/www/html/wordpress
    networks:
      - miapp

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      MYSQL_ROOT_PASSWORD:  
      PMA_HOST: db
    networks:
      - miapp

  # wordpress:
  #   build: wordpress/
  #   ports:
  #     - 90:80
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_NAME: wordpress
  #     WORDPRESS_DB_USER: anton
  #     WORDPRESS_DB_PASSWORD: anton
  #     WORDPRESS_ADMIN_USERNAME: anton
  #     WORDPRESS_ADMIN_PASSWORD: anton
  #   networks:
  #     - miapp

volumes: 
  php:
  wordpress:
networks:
  miapp:
    driver: bridge