-- Creamos la base de datos
CREATE DATABASE IF NOT EXISTS `WP_DB_NAME` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci;

CREATE USER IF NOT EXISTS 'WP_DB_USER'
IDENTIFIED BY 'WP_DB_PASS';

GRANT ALL ON `WP_DB_NAME`.*
TO 'WP_DB_USER';